definitions:
  request.ArticleCreate:
    properties:
      content:
        description: 文章内容
        type: string
      title:
        description: 标题
        type: string
    required:
    - content
    type: object
  request.ArticleEdit:
    properties:
      content:
        description: 文章内容
        type: string
      id:
        type: integer
      title:
        description: 标题
        type: string
    required:
    - content
    - id
    type: object
  request.WordCreate:
    properties:
      category:
        description: 归类ID
        type: integer
      content:
        description: 原本单词
        type: string
      extend:
        description: 扩展批注内容
        type: string
    required:
    - category
    - content
    type: object
  request.WordEdit:
    properties:
      category:
        description: 归类ID
        type: integer
      content:
        description: 原本单词
        type: string
      extend:
        description: 扩展批注内容
        type: string
      id:
        type: integer
    required:
    - category
    - content
    - id
    type: object
info:
  contact: {}
paths:
  /article/createArticle:
    post:
      consumes:
      - application/json
      description: 添加文章
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.ArticleCreate'
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"创建成功"}'
          schema:
            type: string
      summary: 添加文章
      tags:
      - 文章
  /article/editArticle:
    post:
      consumes:
      - application/json
      description: 编辑文章
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.ArticleEdit'
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"编辑成功"}'
          schema:
            type: string
      summary: 编辑文章
      tags:
      - 文章
  /word/createWord:
    post:
      consumes:
      - application/json
      description: 创建词条
      parameters:
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      - description: word
        in: body
        name: word
        required: true
        schema:
          $ref: '#/definitions/request.WordCreate'
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"创建成功"}'
          schema:
            type: string
      summary: 创建词条
      tags:
      - 词条
  /word/editWord:
    post:
      consumes:
      - application/json
      description: 编辑词条
      parameters:
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      - description: word
        in: body
        name: word
        required: true
        schema:
          $ref: '#/definitions/request.WordEdit'
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"编辑成功"}'
          schema:
            type: string
      summary: 编辑词条
      tags:
      - 词条
swagger: "2.0"
